[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  # optional function settings

[edge_functions]
  # optional edge function settings
